name: Build firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libtool-bin gperf python3-docutils autopoint gettext

      - name: Prepare Toolchain
        run: |
          # Tải bộ toolchain đã build sẵn cho chip MT7621 (thay vì tự build)
          mkdir -p toolchain
          wget -qO- https://github.com/padavanlib/padavan-toolchain/releases/download/v1.0/mipsel-linux-uclibc-4.4.x.tar.xz | tar -xJ -C toolchain
          # Đổi tên thư mục cho khớp với mong đợi của script build
          mv toolchain/mipsel-linux-uclibc toolchain/out

      - name: Build Firmware
        run: |
          cd trunk
          # Nạp file config của bạn
          cp ../build.config .config
          
          # Thực hiện build
          ./clear_tree.sh
          ./build_firmware.sh

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: Newifi-D2-Firmware
          path: trunk/images/*.trx
          
