name: Build firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/hadzhioglu/padavan-ng
    defaults: { run: { shell: bash } }
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
    - uses: actions/checkout@v4
      with:
        path: padavan-ng
        
    - name: Build firmware
      run: |
        # Di chuyển vào thư mục trunk
        cd padavan-ng/trunk
        
        # Nạp cấu hình
        cp ../build.config .config
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config
        
        # QUAN TRỌNG: Thiết lập đường dẫn toolchain trỏ về hệ thống của Docker
        # Thay vì để nó tự tìm sai, ta ép nó dùng đường dẫn mặc định trong container
        export PATH=/opt/build/toolchain-mipsel/toolchain-3.4.x/bin:$PATH
        
        chmod +x clear_tree.sh build_firmware.sh
        ./clear_tree.sh
        ./build_firmware.sh
        
        # Tìm file kết quả
        FW_FILE_NAME="$(find images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Newifi-D2-Firmware
        # Đường dẫn này tự động điều chỉnh theo thư mục đã chọn ở trên
        path: |
          padavan-ng/trunk/images/${{ env.FW_FILE_NAME }}
          padavan-ng/images/${{ env.FW_FILE_NAME }}
          
